# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
